GRID_MAP_HEIGHT: int = 15
GRID_MAP_WIDTH: int = 15

MIN_CLEARANCE: float = 1.0
MARGIN_CELL: int = 3
ROUND_NUM: int = 2

PSO_N_PARTICLES: int = 50
PSO_MAX_INIT_ATTEMPTS: int = 20
PSO_MAX_ITER: int = 200
PSO_WEIGHT: float = 0.7
PSO_COGNITIVE_COEFF: float = 1.5
PSO_SOCIAL_COEFF: float = 1.5
PSO_VMAX_K: float = 0.15
PSO_COLLISION_PENALTY: float = 100.0

PSO_USE_SIW: bool = True
PSO_W_MIN: float = 0.4
PSO_W_MAX: float = 0.9

PSO_USE_TVAC: bool = True
PSO_COG_INIT: float = 2.5
PSO_COG_FINAL: float = 0.5
PSO_SOC_INIT: float = 0.5
PSO_SOC_FINAL: float = 2.5

PSO_USE_SOBL: bool = True
PSO_SOBL_MARGIN: float = 3.0
PSO_SOBL_MU: float = 1.0
PSO_SOBL_SIGMA: float = 0.1

PSO_USE_VISIBILITY_SHORTCUTTING: bool = True

PSO_USE_BEZIER: bool = True

PSO_BEZIER_THRESHOLD: float = 45.0
PSO_BEZIER_BLEND_RATIO: float = 0.65
PSO_BEZIER_N_POINTS: int = 9

PSO_USE_LAPLACIAN: bool = True
PSO_LAPLACIAN_ALPHA: float = 0.4
PSO_LAPLACIAN_ROUND: int = 20
