CELL_SIZE = 20
DEFAULT_GRID_HEIGHT = 20
DEFAULT_GRID_WIDTH = 20
WINDOW_PADDING = 50

FONT_SMALL = 20
FONT_NORMAL = 24
FONT_LARGE = 32

START_MENU_WINDOW_HEIGHT = 130
START_MENU_WINDOW_WIDTH = 350

MAP_MENU_WINDOW_HEIGHT = 500
MAP_MENU_WINDOW_WIDTH = 350
MAP_NAME_BUTTON_WIDTH = MAP_MENU_WINDOW_WIDTH - 20
MAP_NAME_BUTTON_HEIGHT = 30
MAP_MENU_PAGINATION = 5

EDITOR_WINDOW_WIDTH = 700
EDITOR_WINDOW_HEIGHT = 430
EDITOR_WINDOW_EXTRA_HEIGHT = 0

SIMULATION_WINDOW_WIDTH = 700
SIMULATION_WINDOW_HEIGHT = 430
SIMULATION_WINDOW_EXTRA_WIDTH = 200
SIMULATION_WINDOW_EXTRA_HEIGHT = 0
